site_name: libvda5050++
repo_url: https://git.openlogisticsfoundation.org/silicon-economy/libraries/vda5050/libvda5050pp
theme:
    name: mkdocs
    highlightjs: true
    hljs_style: github
nav:
    - Home: index.md
    - Install: install.md
    - Dependencies: dependencies.md
    - Quickstart: quickstart.md
    - Configuration: configuration.md
    - API: api.md
    - Doxygen: doxygen/html/index.html
