#!/bin/bash

# Copyright Open Logistics Foundation
# 
# Licensed under the Open Logistics Foundation License 1.3.
# For details on the licensing terms, see the LICENSE file.
# SPDX-License-Identifier: OLFL-1.3
# 

set -xe -o pipefail


sudo -u $USER /usr/bin/cmake -S/src -B/build -GNinja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_COMPILER=/usr/bin/clang++-14 \
  -DLIBVDA5050PP_BUILD_DOCS=ON \
  -DLIBVDA5050PP_INSTALL=ON \
  -DLIBVDA5050PP_CLEAN_INSTALL=ON \
  -DLIBVDA5050PP_BUILD_DEB=ON \
  -DBUILD_TESTING=OFF \
  -DLIBVDA5050PP_FMT_VERSION=8.1.1 \
  -DLIBVDA5050PP_SPDLOG_VERSION=1.9.2 \
  -DLIBVDA5050PP_CATCH2_VERSION=2.13.8 \
  -DLIBVDA5050PP_NLOHMANN_JSON_VERSION=3.10.5 \
  -DCMAKE_INSTALL_PREFIX=/usr \
  $@

sudo -u $USER /usr/bin/cmake --build /build --target package
sudo -u $USER cp /build/*.deb /install/
